#setup renv package library (auto generated by package)
source("renv/activate.R")

#pre-load packages I usually use
library(targets)
library(rmarkdown)
library(dplyr)

#print session info
sessionInfo()
