---
title: "USGS Ephemeral streamgauge QAQC"
output: html_document
date: "`r Sys.Date()`"
author: 'Craig Brinkerhoff'
---

## Info on the USGS gages used for ephemeral stream validations (Fall 2022)
There are some inconsistencies in the use of the term 'ephemeral' in USGS reports that list ephemeral streamgauges, so we used mean annual hydrographs and google maps to verify whether streams are more likely intermittent than ephemeral and flag them as 'eph/int'. These rivers are still used in the discharge model validation, but not in the 'ephemeral number days flowing' validation. Potential reasons these are intermittent rather than ephemeral:

- Persistent baseflow revealed by the mean annual hydrographs. Usually this goes away in the dry season as the river drys up, but even some of these have a perennial baseflow signal.
- Clear visual signs of persistent near-surface water table (as defined [here](https://doi.org/10.1016/B978-0-12-805091-0.00014-1)): riparian zones flush with rooty vegetation, persistent waterlogging, etc. All signs of an intermittently available water table. The hydrographs generally corroborated these visual assessments (small, but persistent, baseflow).
- The saved hydrographs are saved to `cache/check_usgs_eph_hydrographs`.

### USGS ephemeral gages as defined by:
- Rankl, J. G. (2004). Relations between total-sediment load and peak discharge for rainstorm runoff on five ephemeral streams in Wyoming. https://doi.org/10.3133/wri024150
- Heijl, Jr., H. R. (1980). PRELIMINARY APPRAISAL OF EPHEMERAL-STREAMFLOW CHARACTERISTICS AS RELATED TO DRAINAGE AREA, ACTIVE-CHANNEL WIDTH, AND SOILS IN NORTHWESTERN NEW MEXICO. https://doi.org/10.3133/ofr8164
 DeLong, L. L., & Wells, D. K. (1988). Estimating average dissolved-solids yield from basins drained by ephemeral and intermittent streams — Green River basin, Wyoming. https://doi.org/10.3133/wri874222
- Elliott, J. G., & Cartier, K. D. (1986). Hydraulic geometry and streamflow of channels in the Piceance Basin, Rio Blanco and Garfield counties, Colorado (Vol. 85, No. 4118). Department of the Interior, US Geological Survey.
- Schumer, R., Knust, A., & Boyle, D. P. (2014). Characteristics of ephemeral hydrographs in the Southwestern United States. Journal of Hydrologic Engineering, 19(1), 10-17. https://doi.org/10.1061/(ASCE)HE.1943-5584.0000643.

### USGS gages manually removed
- **06268500** confirmed google earth this is an intermittent river that drains a (mostly) ephemeral catchment. Clear signs of persistant near-surface water table and saturation (riparian greenery)
- **06313700** confirmed google earth this is an intermittent river that drains a (mostly) ephemeral catchment. Clear signs of persistant near-surface water table and saturation (riparian greenery)
- **06425750** confirmed google earth this is an intermittent river that drains a (mostly) ephemeral catchment. Clear signs of persistant near-surface water table and saturation (riparian greenery)
- **06425780** confirmed google earth this is an intermittent river that drains a (mostly) ephemeral catchment. Also many perennial pools immediately upstream from (I think) aa coal plant or some mine
- **08331660** persistent baseflow at gage via a USGS report on this gage: Stewart-Deaker, A. E., Moore, S. J., & Stonestrom, D. A. (2007). Stewart-Deaker, A. E., Moore, S. J., & Stonestrom, D. A. (2007). Streamflow, infiltration, and ground-water recharge at Abo Arroyo, New Mexico (Vol. 1703). U.S. Government Printing Office.
- **08477600** confirmed google earth this is an intermittent canal within a city (Silver City, NM). Clear signs of persistant near-surface water table and saturation (riparian greenery). And serious artifical channelization
- **08480595** confirmed in hydrograph to have baseflow year round. google earth also revelas riparizon zones indicative of persistant near-surface water table and saturation
- **09216527** listed in report as eph/int in report
- **09216545** listed in report as eph/int in report
- **09216562** listed in report as eph/int in report
- **09216565** listed in report as eph/int in report
- **09216750** listed in report as eph/int in report
- **09222300** listed in report as eph/int in report
- **09222400** listed in report as eph/int in report
- **09235300** listed in report as eph/int in report
- **09306235** distinct intermittent-style hydrograph with significant baseflow in non-summer and downstream of a spring. Arguably perennila baseflow in the mean annual hydrograph...
- **09306240** distinct intermittent-style hydrograph with significant baseflow in non-summer
- **09508300** distinct intermittent-style hydrograph with significant baseflow in non-summer. Clear signs of persistant near-surface water table and saturation (riparian greenery)
- **09510200** distinct intermittent-style hydrograph with significant baseflow in non-summer.
- **09512450** distinct intermittent-style hydrograph with significant baseflow in non-summer. Arguably perennila baseflow in the mean annual hydrograph...
- **09512600** distinct intermittent-style hydrograph with significant baseflow in non-summer.
- **09512830** distinct intermittent-style hydrograph with significant baseflow in non-summer.
- **09512860** distinct intermittent-style hydrograph with significant baseflow in non-summer.
- **10250800** ephemeral stream BUT it's directly downstream of perrenial waterfall/pool "Devil's Falls"